export const DEFAULT_APP_DATABASE_PROVIDERS = {
  POSTGRES: "postgres",
  NEON: "neon",
} as const;
export type DEFAULT_APP_DATABASE_PROVIDERS_VALUES =
  (typeof DEFAULT_APP_DATABASE_PROVIDERS)[keyof typeof DEFAULT_APP_DATABASE_PROVIDERS];
