# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe68b5e4a88eab465983b36b0ddd33a5"
name = "unmanual"
application_url = "https://i7eo-shopify-app-dev.i7eo.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders"

[auth]
redirect_urls = [
  "https://i7eo-shopify-app-dev.i7eo.com/auth/callback",
  "https://i7eo-shopify-app-dev.i7eo.com/auth/shopify/callback",
  "https://i7eo-shopify-app-dev.i7eo.com/api/auth/callback"
]
