# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3b14c2a2ee39635dba11528ac9e7163"
name = "unmanual"
application_url = "https://your-worker.your-subdomain.workers.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://your-worker.your-subdomain.workers.dev/auth/callback"
]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
