name = "shopify-hono-app"
main = "src/index.ts"
compatibility_date = "2026-05-18"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true

[vars]
APP_RUNTIME = "cloudflare"
# Secrets (set via `wrangler secret put` for production or .env.development for local dev):
# SHOPIFY_APP_KEY
# SHOPIFY_APP_SECRET
# SHOPIFY_APP_URL
# SHOPIFY_API_VERSION
# SCOPES

[[kv_namespaces]]
binding = "sofary"
id = "b5a86d0381b54d3787bc0a53c2bb3198"
