import { HTTP_STATUS_CODES } from "@shamt/envs";

export const VALIDATION_ERROR_CODE =
  HTTP_STATUS_CODES.UNPROCESSABLE_ENTITY.code;

export const VALIDATION_ERROR_MESSAGE =
  HTTP_STATUS_CODES.UNPROCESSABLE_ENTITY.phrase;
