export const DEFAULT_SHOPIFY_APP_MODES = {
  EMBEDDED: "embedded",
  STANDALONE: "standalone",
} as const;
export const DEFAULT_SHOPIFY_APP_MODE = DEFAULT_SHOPIFY_APP_MODES.EMBEDDED;
export type DEFAULT_SHOPIFY_APP_MODES_KEYS =
  keyof typeof DEFAULT_SHOPIFY_APP_MODES;
export type DEFAULT_SHOPIFY_APP_MODES_VALUES =
  (typeof DEFAULT_SHOPIFY_APP_MODES)[DEFAULT_SHOPIFY_APP_MODES_KEYS];
